/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthorizedImport } from './routes/unauthorized'
import { Route as SearchImport } from './routes/search'
import { Route as ProtectedByRoleImport } from './routes/protectedByRole'
import { Route as ProtectedImport } from './routes/protected'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as InvestigationsIndexImport } from './routes/investigations.index'
import { Route as InvestigationsIdImport } from './routes/investigations.$id'
import { Route as InvestigationsIdEditImport } from './routes/investigations_.$id.edit'

// Create/Update Routes

const UnauthorizedRoute = UnauthorizedImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedByRoleRoute = ProtectedByRoleImport.update({
  id: '/protectedByRole',
  path: '/protectedByRole',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InvestigationsIndexRoute = InvestigationsIndexImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRoute,
} as any)

const InvestigationsIdRoute = InvestigationsIdImport.update({
  id: '/investigations/$id',
  path: '/investigations/$id',
  getParentRoute: () => rootRoute,
} as any)

const InvestigationsIdEditRoute = InvestigationsIdEditImport.update({
  id: '/investigations_/$id/edit',
  path: '/investigations/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/protectedByRole': {
      id: '/protectedByRole'
      path: '/protectedByRole'
      fullPath: '/protectedByRole'
      preLoaderRoute: typeof ProtectedByRoleImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedImport
      parentRoute: typeof rootRoute
    }
    '/investigations/$id': {
      id: '/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof InvestigationsIdImport
      parentRoute: typeof rootRoute
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/investigations_/$id/edit': {
      id: '/investigations_/$id/edit'
      path: '/investigations/$id/edit'
      fullPath: '/investigations/$id/edit'
      preLoaderRoute: typeof InvestigationsIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/protected': typeof ProtectedRoute
  '/protectedByRole': typeof ProtectedByRoleRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/investigations/$id/edit': typeof InvestigationsIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/protected': typeof ProtectedRoute
  '/protectedByRole': typeof ProtectedByRoleRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/investigations/$id/edit': typeof InvestigationsIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/protected': typeof ProtectedRoute
  '/protectedByRole': typeof ProtectedByRoleRoute
  '/search': typeof SearchRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/investigations_/$id/edit': typeof InvestigationsIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/protected'
    | '/protectedByRole'
    | '/search'
    | '/unauthorized'
    | '/investigations/$id'
    | '/investigations'
    | '/investigations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/protected'
    | '/protectedByRole'
    | '/search'
    | '/unauthorized'
    | '/investigations/$id'
    | '/investigations'
    | '/investigations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/protected'
    | '/protectedByRole'
    | '/search'
    | '/unauthorized'
    | '/investigations/$id'
    | '/investigations/'
    | '/investigations_/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProtectedRoute: typeof ProtectedRoute
  ProtectedByRoleRoute: typeof ProtectedByRoleRoute
  SearchRoute: typeof SearchRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  InvestigationsIdRoute: typeof InvestigationsIdRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  InvestigationsIdEditRoute: typeof InvestigationsIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProtectedRoute: ProtectedRoute,
  ProtectedByRoleRoute: ProtectedByRoleRoute,
  SearchRoute: SearchRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  InvestigationsIdRoute: InvestigationsIdRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  InvestigationsIdEditRoute: InvestigationsIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/protected",
        "/protectedByRole",
        "/search",
        "/unauthorized",
        "/investigations/$id",
        "/investigations/",
        "/investigations_/$id/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/protected": {
      "filePath": "protected.tsx"
    },
    "/protectedByRole": {
      "filePath": "protectedByRole.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/unauthorized": {
      "filePath": "unauthorized.tsx"
    },
    "/investigations/$id": {
      "filePath": "investigations.$id.tsx"
    },
    "/investigations/": {
      "filePath": "investigations.index.tsx"
    },
    "/investigations_/$id/edit": {
      "filePath": "investigations_.$id.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
