name: .Deploys

on:
  workflow_call:
    inputs:
      ### Required
      release:
        description: Deployment release; usually PR number, test or prod
        required: true
        type: string

      ### Typical / recommended
      autoscaling:
        description: Autoscaling enabled or not for the deployments
        required: false
        type: string
        default: true
      environment:
        description: Environment name; omit for PRs
        required: false
        type: string
      tag:
        description: Container tag; usually PR number
        required: false
        type: string
        default: ${{ github.event.number }}
      triggers:
        description: Paths to trigger a deploy; omit=always; e.g. ('backend/' 'frontend/')
        required: false
        type: string

      ### Usually a bad idea / not recommended
      directory:
        description: 'Chart directory'
        default: 'charts/${{ github.event.repository.name }}'
        required: false
        type: string
      timeout-minutes:
        description: 'Timeout minutes'
        default: 10
        required: false
        type: number
      values:
        description: 'Values file'
        default: 'values.yaml'
        required: false
        type: string
      params:
        description: 'Extra parameters to pass to helm upgrade'
        default: ''
        required: false
        type: string

env:
  repo_release: ${{ github.event.repository.name }}-${{ inputs.release }}
  package_tag: ${{ inputs.tag }}

jobs:
  deploys:
    name: Helm
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          path: source-repo

      - name: Clean up target repository directory
        run: |
          if [ -d "target-repo" ]; then
            rm -rf target-repo
          fi  

      - name: Setup SSH for Target Repository
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.MANIFEST_REPO_DEPLOY_KEY_PUB }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Checkout target repository using SSH
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.GITOPS_REPO}}
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          path: 'target-repo'

      - name: Create new branch in target repository
        run: |
          cd target-repo
          BRANCH_NAME="update-helm-chart-${{ inputs.tag }}"
          git checkout -b $BRANCH_NAME

      - name: Copy folder from source to target
        run: |
          if [ -d "source-repo/charts" ]; then
            mkdir -p target-repo/helm-chart
            cp -r source-repo/charts/* target-repo/helm-chart/
          else
            echo "Directory 'charts' does not exist in source repository"
            exit 1
          fi

      - name: Commit and Push changes
        run: |
          cd target-repo
          git config --global user.name "${{ vars.GLOBAL_USER}}"
          git config --global user.email "${{ vars.GLOBAL_EMAIL}}"
          git add .
          git commit -m "update helm chart ${{ inputs.tag }}"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.BRANCH_NAME }}
          title: "feat: update helm ${{ inputs.tag }}"
          body: "Helm updates"
          token: ${{ secrets.GITOPS_PAT }}  # GITHUB_TOKEN is still needed for PR creation